
spring:
  datasource:
    name: mybatis   #数据库名
    url: jdbc:mysql://localhost:3306/mybatis   #url
    username: root     #用户名
    password: root     #密码
    driver-class-name: com.mysql.jdbc.Driver   #数据库驱动连接

mybatis:
  mapper-locations: classpath:mapper/*.xml   #配置映射文件
  type-aliases-package: com.example.test.bean #配置实体类